name: Build and Push Container Image

on:
  push:
    tags:
      - 'releases/*.*.*'
    branches:
      - 'releases/*.*.*'
  workflow_dispatch:
    inputs:
      manual_branch:
        description: "Specify a branch or tag (e.g., releases/0.1.0)"
        required: false
        default: ""

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.manual_branch || github.ref_name }}

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event.inputs.manual_branch }}" ]; then
            REF="${{ github.event.inputs.manual_branch }}"
          else
            REF="${GITHUB_REF_NAME}"
          fi
          VERSION="${REF#releases/}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "ghcr.io/${{ github.repository_owner }}/toolbox"
          tags: ${{ env.VERSION }} latest
          containerfiles: |
            ./Containerfile
          layers: true

      - name: Push image to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: "ghcr.io"
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}

